function loadData() {
    return [
        new Word("@", "https://www.lifeprint.com/asl101/pages-signs/a/at.htm", ""),
        new Word("ABC's", "https://www.lifeprint.com/asl101/pages-signs/a/abcs.htm", ""),
        new Word("ABOUT", "https://www.lifeprint.com/asl101/pages-signs/a/about.htm", ""),
        new Word("ABOVE", "https://www.lifeprint.com/asl101/pages-signs/a/above.htm", ""),
        new Word("ABUSE", "https://www.lifeprint.com/asl101/pages-signs/a/abuse.htm", ""),
        new Word("ACCEPT", "https://www.lifeprint.com/asl101/pages-signs/a/accept.htm", ""),
        new Word("ACCENT", "https://www.lifeprint.com/asl101/pages-signs/a/accent.htm", ""),
        new Word("ACCIDENT", "https://www.lifeprint.com/asl101/pages-signs/a/accident.htm", ""),
        new Word("accompany-[see WITH]", "https://www.lifeprint.com/asl101/pages-signs/w/with.htm", ""),
        new Word("accountant", "https://www.lifeprint.com/asl101/pages-signs/c/count.htm", ""),
        new Word("ACQUAINTANCE", "https://www.lifeprint.com/asl101/pages-signs/a/acquaintance.htm", ""),
        new Word("ACQUIRE", "https://www.lifeprint.com/asl101/pages-signs/a/acquire.htm", ""),
        new Word("ACROSS", "https://www.lifeprint.com/asl101/pages-signs/a/across.htm", ""),
        new Word("ACT", "https://www.lifeprint.com/asl101/pages-signs/a/act.htm", ""),
        new Word("ACTIVE", "https://www.lifeprint.com/asl101/pages-signs/a/active.htm", ""),
        new Word("ACTOR", "https://www.lifeprint.com/asl101/pages-signs/a/actor.htm", ""),
        new Word("ACTUALLY", "https://www.lifeprint.com/asl101/pages-signs/a/actually.htm", ""),
        new Word("ADD", "https://www.lifeprint.com/asl101/pages-signs/a/add.htm", ""),
        new Word("ADDICT", "https://www.lifeprint.com/asl101/pages-signs/a/addict.htm", ""),
        new Word("add-to", "https://www.lifeprint.com/asl101/pages-signs/a/all-together.htm", ""),
        new Word("ADDRESS", "https://www.lifeprint.com/asl101/pages-signs/a/address.htm", ""),
        new Word("administration-[see MANAGER]", "https://www.lifeprint.com/asl101/pages-signs/m/manager.htm", ""),
        new Word("adopt-[see TAKE-UP]", "https://www.lifeprint.com/asl101/pages-signs/t/take-up.htm", ""),
        new Word("ADOPT", "https://www.lifeprint.com/asl101/pages-signs/a/adopt.htm", ""),
        new Word("ADULT", "https://www.lifeprint.com/asl101/pages-signs/a/adult.htm", ""),
        new Word("advise/advice-[see COUNSEL]", "https://www.lifeprint.com/asl101/pages-signs/c/counsel.htm", ""),
        new Word("AFRAID", "https://www.lifeprint.com/asl101/pages-signs/a/afraid.htm", ""),
        new Word("AFRICA", "https://www.lifeprint.com/asl101/pages-signs/a/africa.htm", ""),
        new Word("AFTER", "https://www.lifeprint.com/asl101/pages-signs/a/after.htm", ""),
        new Word("AFTERNOON", "https://www.lifeprint.com/asl101/pages-signs/a/afternoon.htm", ""),
        new Word("AGAIN", "https://www.lifeprint.com/asl101/pages-signs/a/again.htm", ""),
        new Word("AGAINST", "https://www.lifeprint.com/asl101/pages-signs/a/against.htm", ""),
        new Word("AGENT", "https://www.lifeprint.com/asl101/pages-signs/a/agent.htm", ""),
        new Word("AGGRESSIVE", "https://www.lifeprint.com/asl101/pages-signs/a/aggressive.htm", ""),
        new Word("AGREE", "https://www.lifeprint.com/asl101/pages-signs/a/agree.htm", ""),
        new Word("AIDE", "https://www.lifeprint.com/asl101/pages-signs/a/aide.htm", ""),
        new Word("AIR", "https://www.lifeprint.com/asl101/pages-signs/a/air.htm", ""),
        new Word("AIRPLANE", "https://www.lifeprint.com/asl101/pages-signs/a/airplane.htm", ""),
        new Word("ALCOHOL", "https://www.lifeprint.com/asl101/pages-signs/a/alcohol.htm", ""),
        new Word("ALCOHOLIC", "https://www.lifeprint.com/asl101/pages-signs/a/alcoholic.htm", ""),
        new Word("allergy", "https://www.lifeprint.com/asl101/pages-signs/o/opposite.htm", ""),
        new Word("ALL", "https://www.lifeprint.com/asl101/pages-signs/a/all.htm", ""),
        new Word("ALLIGATOR", "https://www.lifeprint.com/asl101/pages-signs/a/alligator.htm", ""),
        new Word("all-over/-dom-[see FIELD]", "https://www.lifeprint.com/asl101/pages-signs/f/field.htm", ""),
        new Word("ALLOW", "https://www.lifeprint.com/asl101/pages-signs/a/allow.htm", ""),
        new Word("almost-[see EASY]", "https://www.lifeprint.com/asl101/pages-signs/a/almost.htm", ""),
        new Word("alone-[see SINGLE]", "https://www.lifeprint.com/asl101/pages-signs/s/single.htm", ""),
        new Word("A-LOT", "https://www.lifeprint.com/asl101/pages-signs/a/a-lot.htm", ""),
        new Word("ALMOST", "https://www.lifeprint.com/asl101/pages-signs/a/almost.htm", ""),
        new Word("ALOHA", "https://www.lifeprint.com/asl101/pages-signs/a/aloha.htm", ""),
        new Word("ALPHABET", "https://www.lifeprint.com/asl101/pages-signs/a/alphabet.htm", ""),
        new Word("ALRIGHT", "https://www.lifeprint.com/asl101/pages-signs/a/alright.htm", ""),
        new Word("ALSO", "https://www.lifeprint.com/asl101/pages-signs/a/also.htm", ""),
        new Word("ALTOGETHER", "https://www.lifeprint.com/asl101/pages-signs/a/altogether.htm", ""),
        new Word("ALWAYS", "https://www.lifeprint.com/asl101/pages-signs/a/always.htm", ""),
        new Word("AM", "https://www.lifeprint.com/asl101/pages-signs/a/am.htm", ""),
        new Word("ambulance-[see LIGHT]", "https://www.lifeprint.com/asl101/pages-signs/l/light.htm", ""),
        new Word("AMERICA", "https://www.lifeprint.com/asl101/pages-signs/a/america.htm", ""),
        new Word("American", "https://www.lifeprint.com/asl101/pages-signs/a/american.htm", ""),
        new Word("American: Native American", "https://www.lifeprint.com/asl101/pages-signs/a/american-indian.htm", ""),
        new Word("Amish", "https://www.lifeprint.com/asl101/pages-signs/a/amish.htm", ""),
        new Word("AMOUNT", "https://www.lifeprint.com/asl101/pages-signs/a/amount.htm", ""),
        new Word("an", "https://www.lifeprint.com/asl101/pages-signs/a/an.htm", ""),
        new Word("AND", "https://www.lifeprint.com/asl101/pages-signs/a/and.htm", ""),
        new Word("ANGEL", "https://www.lifeprint.com/asl101/pages-signs/a/angel.htm", ""),
        new Word("ANGRY", "https://www.lifeprint.com/asl101/pages-signs/a/angry.htm", ""),
        new Word("ANIMAL", "https://www.lifeprint.com/asl101/pages-signs/a/animal.htm", ""),
        new Word("ANIMALS", "https://www.lifeprint.com/asl101/pages-signs/a/animals.htm", ""),
        new Word("annually", "https://www.lifeprint.com/asl101/pages-signs/y/yearadvanced.htm", ""),
        new Word("ANSWER", "https://www.lifeprint.com/asl101/pages-signs/a/answer.htm", ""),
        new Word("ANT", "https://www.lifeprint.com/asl101/pages-signs/a/ant.htm", ""),
        new Word("ANTHROPOLOGY", "https://www.lifeprint.com/asl101/pages-signs/a/anthropology.htm", ""),
        new Word("ANY", "https://www.lifeprint.com/asl101/pages-signs/a/any.htm", ""),
        new Word("ANXIOUS", "https://www.lifeprint.com/asl101/pages-signs/a/anxious.htm", ""),
        new Word("APARTMENT", "https://www.lifeprint.com/asl101/pages-signs/a/apartment.htm", ""),
        new Word("APE", "https://www.lifeprint.com/asl101/pages-signs/a/ape.htm", ""),
        new Word("APOSTROPHE", "https://www.lifeprint.com/asl101/pages-signs/a/apostrophe.htm", ""),
        new Word("APOSTROPHE S", "https://www.lifeprint.com/asl101/pages-signs/a/apostrophe-s.htm", ""),
        new Word("APPEAR", "https://www.lifeprint.com/asl101/pages-signs/a/appear.htm", ""),
        new Word("APPLAUSE", "https://www.lifeprint.com/asl101/pages-signs/a/applause.htm", ""),
        new Word("APPLE", "https://www.lifeprint.com/asl101/pages-signs/a/apple.htm", ""),
        new Word("APPLY", "https://www.lifeprint.com/asl101/pages-signs/a/apply.htm", ""),
        new Word("APPOINTMENT", "https://www.lifeprint.com/asl101/pages-signs/a/appointment.htm", ""),
        new Word("APPRECIATE", "https://www.lifeprint.com/asl101/pages-signs/e/enjoy.htm", ""),
        new Word("APPROXIMATELY", "https://www.lifeprint.com/asl101/pages-signs/a/approximately.htm", ""),
        new Word("ARE", "https://www.lifeprint.com/asl101/pages-signs/a/are.htm", ""),
        new Word("AREA", "https://www.lifeprint.com/asl101/pages-signs/a/area.htm", ""),
        new Word("ARGUE", "https://www.lifeprint.com/asl101/pages-signs/a/argue.htm", ""),
        new Word("ARIZONA", "https://www.lifeprint.com/asl101/pages-signs/a/arizona.htm", ""),
        new Word("ARMY", "https://www.lifeprint.com/asl101/pages-signs/a/army.htm", ""),
        new Word("around-[see APPROXIMATELY]", "https://www.lifeprint.com/asl101/pages-signs/a/approximately.htm", ""),
        new Word("ARRIVE", "https://www.lifeprint.com/asl101/pages-signs/a/arrive.htm", ""),
        new Word("art-[see DRAW]", "https://www.lifeprint.com/asl101/pages-signs/d/draw.htm", ""),
        new Word("ARTHRITIS", "https://www.lifeprint.com/asl101/pages-signs/a/arthritis.htm", ""),
        new Word("article/column-[see CL:C]", "https://www.lifeprint.com/asl101/pages-signs/c/clc.htm", ""),
        new Word("ARTICLE", "https://www.lifeprint.com/asl101/pages-signs/a/article.htm", ""),
        new Word("ASK", "https://www.lifeprint.com/asl101/pages-signs/a/ask.htm", ""),
        new Word("ASSAULT", "https://www.lifeprint.com/asl101/pages-signs/a/assault.htm", ""),
        new Word("ASSIGNMENT", "https://www.lifeprint.com/asl101/pages-signs/a/assignment.htm", ""),
        new Word("ASTERISK", "https://www.lifeprint.com/asl101/pages-signs/a/asterisk.htm", ""),
        new Word("ATM", "https://www.lifeprint.com/asl101/pages-signs/a/atm.htm", ""),
        new Word("ATLANTA", "https://www.lifeprint.com/asl101/pages-signs/a/atlanta.htm", ""),
        new Word("ATTENTION", "https://www.lifeprint.com/asl101/pages-signs/a/attention.htm", ""),
        new Word("AUDIENCE", "https://www.lifeprint.com/asl101/pages-signs/a/audience.htm", ""),
        new Word("AUNT", "https://www.lifeprint.com/asl101/pages-signs/a/aunt.htm", ""),
        new Word("AUSTRALIA", "https://www.lifeprint.com/asl101/pages-signs/a/australia.htm", ""),
        new Word("AUTISM", "https://www.lifeprint.com/asl101/pages-signs/a/autism.htm", ""),
        new Word("AUTUMN", "https://www.lifeprint.com/asl101/pages-signs/a/autumn.htm", ""),
        new Word("AVERAGE", "https://www.lifeprint.com/asl101/pages-signs/a/average.htm", ""),
        new Word("AVOCADO", "https://www.lifeprint.com/asl101/pages-signs/a/avocado.htm", ""),
        new Word("AWESOME", "https://www.lifeprint.com/asl101/pages-signs/a/awesome.htm", ""),
        new Word("AWFUL", "https://www.lifeprint.com/asl101/pages-signs/a/awful.htm", ""),
        new Word("AWKWARD", "https://www.lifeprint.com/asl101/pages-signs/a/awkward.htm", ""),
    ]
}